name: Naukri Profile Auto Update

on:
  schedule:
    - cron: "30 0 * * *" # 6:00 AM IST (00:30 AM UTC)
    - cron: "30 3 * * *" # 9:00 AM IST (03:30 AM UTC)
    - cron: "30 8 * * *" # 2:00 PM IST (08:30 AM UTC)
  workflow_dispatch: # Also allows manual run if needed

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Adjust your version if needed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python your_script_name.py
