name: Naukri Profile Auto Update

on:
  schedule:
    - cron: "30 0 * * *"
    - cron: "30 3 * * *"
    - cron: "30 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean test
